# Generated by Django 3.2.9 on 2021-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Secondname', models.CharField(max_length=100)),
                ('Phonenumber', models.IntegerField()),
                ('EmailId', models.EmailField(max_length=254)),
                ('Feedback', models.TextField()),
            ],
        ),
    ]
