# Generated by Django 3.2.9 on 2021-12-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('Number', models.IntegerField(default='', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.IntegerField(default='', max_length=100)),
            ],
        ),
    ]
